name: CI

on: [push]

env:
  MPI_DIR=/usr
  DAGMC_ROOT=$HOME/DAGMC
  HDF5_ROOT=/usr
  OMP_NUM_THREADS=2
  OPENMC_CROSS_SECTIONS=$HOME/nndc_hdf5/cross_sections.xml
  OPENMC_ENDF_DATA=$HOME/endf-b-vii.1
  PATH=$PATH:$HOME/NJOY2016/build
  COVERALLS_PARALLEL=true
  NUMPY_EXPERIMENTAL_ARRAY_FUNCTION=0


jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Apt dependencies
        run: |
          sudo apt -y update
          sudo apt install -y mpich \
                              libmpich-dev \
                              libhdf5-serial-dev \
                              libhdf5-mpich-dev \
                              libeigen3-dev
        
