name: Format Check

on: [push, pull_request]
jobs:
  clang-format-check:
    name: Clang-format Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check for C++ code.
      uses: jidicula/clang-format-action@v4.11.0
      with:
        clang-format-version: '13'
        check-path: 'src'